### ISSUE TITLE
KeyError: 'depth'

### ISSUE THREAD

**Issue by CaroZ655** [johnomics/tapestry#12]
In installed Tapestry in a Conda environment on our HPC and am trying to run :

```
weave -a /path/M17.racon3.medaka.pilon.fasta -r /path/ancestor.17.nanopore.nanofilt.fastq.gz  -t TTAGGG \
-o /path/pilon_rounds/tapestry_output -c 10 -l 5000
```

But I keep getting the following error : 
```
2025-11-06 15:06:14 WARNING	Output directory /path/tapestry_output found, will use existing analysis files if present and up-to-date, but overwrite reports
2025-11-06 15:06:14 INFO	Loading genome assembly
2025-11-06 15:06:14 INFO	Loaded 53 contigs from /path/M17.racon3.medaka.pilon.fasta
2025-11-06 15:06:14 INFO	Ploidy window size set to 100000 based on assembly N50 length 2359087
2025-11-06 15:06:14 INFO	Sampling 50 times coverage of 40.0 Mb assembly from >5000bp reads in /path/ancestor.17.nanopore.nanofilt.fastq.gz

  0%|          | 0/50 [00:00<?, ?it/s]
  2%|▏         | 1/50 [00:06<05:23,  6.60s/it]
  4%|▍         | 2/50 [00:19<06:47,  8.49s/it]
  6%|▌         | 3/50 [00:32<07:41,  9.82s/it]
  8%|▊         | 4/50 [00:45<08:16, 10.80s/it]
 10%|█         | 5/50 [00:58<08:36, 11.47s/it]
 12%|█▏        | 6/50 [01:11<08:46, 11.96s/it]
 14%|█▍        | 7/50 [01:24<08:46, 12.25s/it]
 16%|█▌        | 8/50 [01:37<08:43, 12.46s/it]
 18%|█▊        | 9/50 [01:50<08:37, 12.62s/it]
 20%|██        | 10/50 [02:03<08:29, 12.73s/it]
 22%|██▏       | 11/50 [02:16<08:18, 12.78s/it]
 24%|██▍       | 12/50 [02:29<08:06, 12.79s/it]
 26%|██▌       | 13/50 [02:42<07:54, 12.83s/it]
 28%|██▊       | 14/50 [02:55<07:42, 12.84s/it]
 30%|███       | 15/50 [03:07<07:29, 12.84s/it]
 32%|███▏      | 16/50 [03:20<07:15, 12.81s/it]
 34%|███▍      | 17/50 [03:30<06:34, 11.94s/it]
                                               
2025-11-06 15:09:48 INFO	Wrote 89969 reads (671822300 bases, 17 times coverage) to /path/tapestry_output/reads.fastq.gz
2025-11-06 15:09:48 WARNING	Only found 17 times coverage in reads longer than 5000, not 50 times; consider reducing minimum read length (-l)
2025-11-06 15:09:48 INFO	Aligning reads /path/tapestry_output/reads.fastq.gz to assembly
2025-11-06 15:11:38 INFO	Indexing /path/tapestry_output/reads_assembly.bam
2025-11-06 15:11:41 INFO	Aligning contigs /path/tapestry_output/assembly.fasta to assembly
2025-11-06 15:11:47 INFO	Indexing /path/tapestry_output/contigs_assembly.bam
2025-11-06 15:13:33 INFO	Building alignments database /path/tapestry_output/alignments.db
2025-11-06 15:16:12 INFO	Loading contig alignments into database
2025-11-06 15:16:14 INFO	Loading read alignments into database
2025-11-06 15:16:29 INFO	Finding neighbouring alignments

  0%|          | 0/7158 [00:00<?, ? alignments/s]
 14%|█▍        | 1000/7158 [00:09<00:59, 104.15 alignments/s]
 28%|██▊       | 2000/7158 [00:20<00:50, 101.18 alignments/s]
 42%|████▏     | 3000/7158 [00:29<00:40, 102.99 alignments/s]
 56%|█████▌    | 4000/7158 [00:37<00:29, 108.16 alignments/s]
 70%|██████▉   | 5000/7158 [01:02<00:30, 71.23 alignments/s] 
 84%|████████▍ | 6000/7158 [01:11<00:14, 80.54 alignments/s]
 98%|█████████▊| 7000/7158 [01:19<00:01, 89.47 alignments/s]
                                                            
2025-11-06 15:18:03 INFO	Processing 53 contigs
Tapestry version 1.0.1
Dependencies
minimap2       2.24-r1122     /home/caroz/mambaforge/envs/tapestry_env/bin/minimap2
samtools       1.15.1         /home/caroz/mambaforge/envs/tapestry_env/bin/samtools


Welcome to Tapestry!

Assembly to validate	/path/M17.racon3.medaka.pilon.fasta
Reads to sample from	/path/ancestor.17.nanopore.nanofilt.fastq.gz
Coverage to sample	50
Minimum read length	5000
Telomere sequence(s)	TTAGGG
Minimum contig alignment	2000
Output directory	/path/pilon_rounds/tapestry_output


Processing contigs:   0%|          | 0/53 [00:00<?, ? contig/s]multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/caroz/mambaforge/envs/tapestry_env/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 2657, in get_loc
    return self._engine.get_loc(key)
  File "pandas/_libs/index.pyx", line 108, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 132, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1601, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1608, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'depth'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/caroz/mambaforge/envs/tapestry_env/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/home/caroz/mambaforge/envs/tapestry_env/lib/python3.6/site-packages/tapestry/contig.py", line 40, in process_contig
    contig.process()
  File "/home/caroz/mambaforge/envs/tapestry_env/lib/python3.6/site-packages/tapestry/contig.py", line 114, in process
    self.median_read_depth = self.median_depth(self.read_depths)
  File "/home/caroz/mambaforge/envs/tapestry_env/lib/python3.6/site-packages/tapestry/contig.py", line 152, in median_depth
    return depths['depth'].median() if depths is not None else 0
  File "/home/caroz/mambaforge/envs/tapestry_env/lib/python3.6/site-packages/pandas/core/frame.py", line 2927, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/home/caroz/mambaforge/envs/tapestry_env/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 2659, in get_loc
    return self._engine.get_loc(self._maybe_cast_indexer(key))
  File "pandas/_libs/index.pyx", line 108, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 132, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1601, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1608, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'depth'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/caroz/mambaforge/envs/tapestry_env/bin/weave", line 45, in <module>
    assembly = Assembly(args.assembly, args.reads, args.telomere, args.output, args.cores, args.depth, args.length, args.windowsize, args.forcereadoutput, args.mincontigalignment)
  File "/home/caroz/mambaforge/envs/tapestry_env/lib/python3.6/site-packages/tapestry/assembly.py", line 109, in __init__
    self.process_contigs()
  File "/home/caroz/mambaforge/envs/tapestry_env/lib/python3.6/site-packages/tapestry/assembly.py", line 316, in process_contigs
    for contig in tapestry_tqdm(p.imap(process_contig, self.contigs.values()), total=len(self.contigs), desc="Processing contigs"):
  File "/home/caroz/mambaforge/envs/tapestry_env/lib/python3.6/site-packages/tqdm-4.7.2-py3.6.egg/tqdm/_tqdm.py", line 594, in __iter__
  File "/home/caroz/mambaforge/envs/tapestry_env/lib/python3.6/multiprocessing/pool.py", line 735, in next
    raise value
KeyError: 'depth'
```
I changed the depth to -d 17, but it gave the same error.

**Comment by johnomics** [comment]
Hi @CaroZ655, sorry about this error. What were the INFO and WARNING lines ('Wrote x reads...', 'Only found x times coverage...' etc) when you ran with -d 17? How many reads and bases are there in your original FASTQ file (ancestor.17.nanopore.nanofilt.fastq.gz)? If you are still seeing a 'Only found x times coverage' warning, please try reducing -d and also minimum read length (-l) until this warning goes away. Do you still get the error?

**Comment by CaroZ655** [comment]
The error message was the same when I ran the same script with d -17. So I re-ran with -l 100 and d- 17 :

```
2025-11-10 00:30:15 WARNING	Output directory /path/tapestry_output found, will use existing analysis files if present and up-to-date, but overwrite reports
2025-11-10 00:30:15 INFO	Loading genome assembly
2025-11-10 00:30:17 INFO	Loaded 53 contigs from /paths/M17.racon3.medaka.pilon.fasta
2025-11-10 00:30:17 INFO	Ploidy window size set to 100000 based on assembly N50 length 2359087
2025-11-10 00:30:17 INFO	Sampling 17 times coverage of 40.0 Mb assembly from >100bp reads in /path/ancestor.17.nanopore.nanofilt.fastq.gz

  0%|          | 0/17 [00:00<?, ?it/s]
  6%|▌         | 1/17 [00:06<01:48,  6.79s/it]
 12%|█▏        | 2/17 [00:20<02:11,  8.76s/it]
 18%|█▊        | 3/17 [00:33<02:22, 10.21s/it]
 24%|██▎       | 4/17 [00:46<02:24, 11.08s/it]
 29%|██▉       | 5/17 [01:00<02:20, 11.75s/it]
 35%|███▌      | 6/17 [01:13<02:14, 12.26s/it]
 41%|████      | 7/17 [01:26<02:05, 12.60s/it]
 47%|████▋     | 8/17 [01:40<01:55, 12.78s/it]
 53%|█████▎    | 9/17 [01:53<01:43, 12.95s/it]
 59%|█████▉    | 10/17 [02:06<01:31, 13.02s/it]
 65%|██████▍   | 11/17 [02:19<01:18, 13.07s/it]
 71%|███████   | 12/17 [02:33<01:05, 13.10s/it]
 76%|███████▋  | 13/17 [02:45<00:51, 12.99s/it]
 82%|████████▏ | 14/17 [02:59<00:39, 13.07s/it]
 88%|████████▊ | 15/17 [03:12<00:26, 13.11s/it]
 94%|█████████▍| 16/17 [03:25<00:13, 13.14s/it]
100%|██████████| 17/17 [03:35<00:00, 12.22s/it]
                                               
2025-11-10 00:33:53 INFO	Wrote 88515 reads (659809543 bases, 17 times coverage) to path/tapestry_output/reads.fastq.gz
2025-11-10 00:33:53 INFO	Aligning reads path/tapestry_output/reads.fastq.gz to assembly
2025-11-10 00:35:51 INFO	Indexing path/tapestry_output/reads_assembly.bam
2025-11-10 00:35:52 INFO	Aligning contigs /path/tapestry_output/assembly.fasta to assembly
2025-11-10 00:35:58 INFO	Indexing /path/tapestry_output/contigs_assembly.bam
2025-11-10 00:35:59 INFO	Building alignments database /path/tapestry_output/alignments.db
2025-11-10 00:57:29 INFO	Loading contig alignments into database
2025-11-10 00:57:31 INFO	Loading read alignments into database
2025-11-10 01:05:20 INFO	Finding neighbouring alignments

  0%|          | 0/7058 [00:00<?, ? alignments/s]
 14%|█▍        | 1000/7058 [00:11<01:07, 89.47 alignments/s]
 28%|██▊       | 2000/7058 [00:29<01:07, 75.31 alignments/s]
 43%|████▎     | 3000/7058 [00:44<00:56, 72.16 alignments/s]
 57%|█████▋    | 4000/7058 [00:51<00:35, 85.05 alignments/s]
 71%|███████   | 5000/7058 [00:58<00:21, 96.90 alignments/s]
 85%|████████▌ | 6000/7058 [01:08<00:10, 96.21 alignments/s]
 99%|█████████▉| 7000/7058 [01:16<00:00, 106.39 alignments/s]
                                                             
2025-11-10 01:06:40 INFO	Processing 53 contigs
Tapestry version 1.0.1
Dependencies
minimap2       2.24-r1122     /home/caroz/mambaforge/envs/tapestry_env/bin/minimap2
samtools       1.15.1         /home/caroz/mambaforge/envs/tapestry_env/bin/samtools


Welcome to Tapestry!

Assembly to validate	/path/M17.racon3.medaka.pilon.fasta
Reads to sample from	/path/ancestor.17.nanopore.nanofilt.fastq.gz
Coverage to sample	17
Minimum read length	100
Telomere sequence(s)	TTAGGG
Minimum contig alignment	2000
Output directory	/path/tapestry_output


Processing contigs:   0%|          | 0/53 [00:00<?, ? contig/s]multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/caroz/mambaforge/envs/tapestry_env/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 2898, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 70, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 101, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1675, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1683, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'depth'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/caroz/mambaforge/envs/tapestry_env/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/home/caroz/mambaforge/envs/tapestry_env/lib/python3.6/site-packages/tapestry/contig.py", line 40, in process_contig
    contig.process()
  File "/home/caroz/mambaforge/envs/tapestry_env/lib/python3.6/site-packages/tapestry/contig.py", line 114, in process
    self.median_read_depth = self.median_depth(self.read_depths)
  File "/home/caroz/mambaforge/envs/tapestry_env/lib/python3.6/site-packages/tapestry/contig.py", line 152, in median_depth
    return depths['depth'].median() if depths is not None else 0
  File "/home/caroz/mambaforge/envs/tapestry_env/lib/python3.6/site-packages/pandas/core/frame.py", line 2906, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/home/caroz/mambaforge/envs/tapestry_env/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 2900, in get_loc
    raise KeyError(key) from err
KeyError: 'depth'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/caroz/mambaforge/envs/tapestry_env/bin/weave", line 45, in <module>
    assembly = Assembly(args.assembly, args.reads, args.telomere, args.output, args.cores, args.depth, args.length, args.windowsize, args.forcereadoutput, args.mincontigalignment)
  File "/home/caroz/mambaforge/envs/tapestry_env/lib/python3.6/site-packages/tapestry/assembly.py", line 109, in __init__
    self.process_contigs()
  File "/home/caroz/mambaforge/envs/tapestry_env/lib/python3.6/site-packages/tapestry/assembly.py", line 316, in process_contigs
    for contig in tapestry_tqdm(p.imap(process_contig, self.contigs.values()), total=len(self.contigs), desc="Processing contigs"):
  File "/home/caroz/mambaforge/envs/tapestry_env/lib/python3.6/site-packages/tqdm-4.7.2-py3.6.egg/tqdm/_tqdm.py", line 594, in __iter__
  File "/home/caroz/mambaforge/envs/tapestry_env/lib/python3.6/multiprocessing/pool.py", line 735, in next
    raise value
KeyError: 'depth'

```

**Comment by CaroZ655** [comment]
... sorry I forgot to provide some information you were asking for : 

```
cat /path/ancestor.17.nanopore.nanofilt.fastq.gz | paste - - - - | cut -f 2 | tr -d '\n' | wc -c
68490291 # this should be the number of bases from what I understand 

 wc -l /path/ancestor.17.nanopore.nanofilt.fastq.gz
 1977205

Divided by 4 = 494301.2 # should be the number of reads
```

**Comment by johnomics** [comment]
Hi @CaroZ655 - sorry, I'm unable to reproduce this error. Please could you try editing the file '/home/caroz/mambaforge/envs/tapestry_env/lib/python3.6/site-packages/tapestry/contig.py' - find the `median_depth` function and change the code to:

```
    def median_depth(self, depths):
        return depths['depth'].median() if depths is not None and 'depth' in depths.columns else 0
```

I hope this will work around the 'depth' KeyError, but I can't see what would trigger that error. It means no read alignments have been recorded for the contig being processed (which looks like it's the first contig), but I don't know why I've not seen that error before. Possibly something has changed in a package Tapestry uses.

Please could you check your FASTQ file again, with a tool that understands FASTQ files such as seqkit? (Try seqkit stats: https://bioinf.shenwei.me/seqkit/usage/#stats) Tapestry seems to be processing it OK now but the number of bases it is reporting (659809543) is higher than the total number of bases in your `wc -c` call (68490291). Also, the number of lines in the FASTQ file should be an exact multiple of 4.

**Comment by CaroZ655** [comment]
Done !

This time : 
```
weave -a /path/M17.racon3.medaka.pilon.fasta \
      -r path/ancestor.17.nanopore.nanofilt.fastq.gz \
      -t TTAGGG -o /path/tapestry_output -c 10 -l 100 -d 17
```

Gave me an other error : 

```
2025-11-17 17:14:04 WARNING	Output directory /path/tapestry_output found, will use existing analysis files if present and up-to-date, but overwrite reports
2025-11-17 17:14:04 INFO	Loading genome assembly
2025-11-17 17:14:06 INFO	Loaded 53 contigs from /path/M17.racon3.medaka.pilon.fasta
2025-11-17 17:14:06 INFO	Ploidy window size set to 100000 based on assembly N50 length 2359087
2025-11-17 17:14:06 INFO	Sampling 17 times coverage of 40.0 Mb assembly from >100bp reads in /path/ancestor.17.nanopore.nanofilt.fastq.gz

  0%|          | 0/17 [00:00<?, ?it/s]
  6%|▌         | 1/17 [00:06<01:43,  6.48s/it]
 12%|█▏        | 2/17 [00:19<02:06,  8.45s/it]
 18%|█▊        | 3/17 [00:32<02:17,  9.79s/it]
 24%|██▎       | 4/17 [00:45<02:19, 10.73s/it]
 29%|██▉       | 5/17 [00:58<02:16, 11.39s/it]
 35%|███▌      | 6/17 [01:11<02:11, 11.92s/it]
 41%|████      | 7/17 [01:24<02:02, 12.23s/it]
 47%|████▋     | 8/17 [01:37<01:52, 12.45s/it]
 53%|█████▎    | 9/17 [01:50<01:40, 12.58s/it]
 59%|█████▉    | 10/17 [02:03<01:28, 12.67s/it]
 65%|██████▍   | 11/17 [02:16<01:16, 12.74s/it]
 71%|███████   | 12/17 [02:28<01:03, 12.77s/it]
 76%|███████▋  | 13/17 [02:41<00:51, 12.80s/it]
 82%|████████▏ | 14/17 [02:54<00:38, 12.80s/it]
 88%|████████▊ | 15/17 [03:07<00:25, 12.79s/it]
 94%|█████████▍| 16/17 [03:20<00:12, 12.81s/it]
100%|██████████| 17/17 [03:30<00:00, 11.94s/it]
                                               
2025-11-17 17:17:36 INFO	Wrote 88515 reads (659809543 bases, 17 times coverage) to /path/reads.fastq.gz
2025-11-17 17:17:36 INFO	Aligning reads /path/reads.fastq.gz to assembly
2025-11-17 17:28:29 INFO	Indexing /path/reads_assembly.bam
2025-11-17 17:28:32 INFO	Aligning contigs /path/assembly.fasta to assembly
2025-11-17 17:29:19 INFO	Indexing /path/contigs_assembly.bam
2025-11-17 17:29:20 INFO	Building alignments database /path/tapestry_output/alignments.db
2025-11-17 17:29:33 INFO	Loading contig alignments into database
2025-11-17 17:32:50 INFO	Loading read alignments into database
2025-11-17 18:00:24 INFO	Finding neighbouring alignments

  0%|          | 0/7058 [00:00<?, ? alignments/s]
 14%|█▍        | 1000/7058 [13:47<1:23:32,  1.21 alignments/s]
 28%|██▊       | 2000/7058 [18:01<55:14,  1.53 alignments/s]  
 43%|████▎     | 3000/7058 [18:35<31:43,  2.13 alignments/s]
 57%|█████▋    | 4000/7058 [18:42<16:50,  3.03 alignments/s]
 71%|███████   | 5000/7058 [18:49<08:00,  4.29 alignments/s]
 85%|████████▌ | 6000/7058 [19:48<03:11,  5.52 alignments/s]
 99%|█████████▉| 7000/7058 [19:56<00:07,  7.74 alignments/s]
                                                            
2025-11-17 18:21:44 INFO	Processing 53 contigs
Tapestry version 1.0.1
Dependencies
minimap2       2.24-r1122     /home/caroz/mambaforge/envs/tapestry_env/bin/minimap2
samtools       1.15.1         /home/caroz/mambaforge/envs/tapestry_env/bin/samtools


Welcome to Tapestry!

Assembly to validate	/path/M17.racon3.medaka.pilon.fasta
Reads to sample from	/path/ancestor.17.nanopore.nanofilt.fastq.gz
Coverage to sample	17
Minimum read length	100
Telomere sequence(s)	TTAGGG
Minimum contig alignment	2000
Output directory	/pathtapestry_output


Processing contigs:   0%|          | 0/53 [00:00<?, ? contig/s]multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/caroz/mambaforge/envs/tapestry_env/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/home/caroz/mambaforge/envs/tapestry_env/lib/python3.6/site-packages/tapestry/contig.py", line 40, in process_contig
    contig.process()
  File "/home/caroz/mambaforge/envs/tapestry_env/lib/python3.6/site-packages/tapestry/contig.py", line 121, in process
    self.read_alignments = self.plot_read_alignments()
  File "/home/caroz/mambaforge/envs/tapestry_env/lib/python3.6/site-packages/tapestry/contig.py", line 267, in plot_read_alignments
    start_distance, end_distance = a.left_clip, a.right_clip
  File "/home/caroz/mambaforge/envs/tapestry_env/lib/python3.6/site-packages/pandas/core/generic.py", line 5141, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'Series' object has no attribute 'left_clip'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/caroz/mambaforge/envs/tapestry_env/bin/weave", line 45, in <module>
    assembly = Assembly(args.assembly, args.reads, args.telomere, args.output, args.cores, args.depth, args.length, args.windowsize, args.forcereadoutput, args.mincontigalignment)
  File "/home/caroz/mambaforge/envs/tapestry_env/lib/python3.6/site-packages/tapestry/assembly.py", line 109, in __init__
    self.process_contigs()
  File "/home/caroz/mambaforge/envs/tapestry_env/lib/python3.6/site-packages/tapestry/assembly.py", line 316, in process_contigs
    for contig in tapestry_tqdm(p.imap(process_contig, self.contigs.values()), total=len(self.contigs), desc="Processing contigs"):
  File "/home/caroz/mambaforge/envs/tapestry_env/lib/python3.6/site-packages/tqdm-4.7.2-py3.6.egg/tqdm/_tqdm.py", line 594, in __iter__
  File "/home/caroz/mambaforge/envs/tapestry_env/lib/python3.6/multiprocessing/pool.py", line 735, in next
    raise value
AttributeError: 'Series' object has no attribute 'left_clip'
```

**Comment by CaroZ655** [comment]
... also 

```
seqkit stats /path/ancestor.17.nanopore.nanofilt.fastq.gz
file                                                              format  type  num_seqs      sum_len  min_len  avg_len    max_len
/path/ancestor.17.nanopore.nanofilt.fastq.gz                      FASTQ   DNA     89,969  671,822,300    5,000  7,467.3  1,120,062
```

**Comment by johnomics** [comment]
Hi @CaroZ655 , I'm sorry, I've looked into this again and I still can't replicate this error. Some options:
1. Possibly try using a read depth of 10 (-d 10), as 17 is the size of your total FASTQ file and that might be causing some problems (though I'm not sure what).
2. Please could you say which versions of Pandas and SQLalchemy you have installed in your Tapestry mamba environment? The problems are coming up because a Pandas DataFrame is not getting filled from an SQLalchemy query response. This could be because there is something in your data that I haven't seen before and so Tapestry isn't handling it correctly (see below), but it could also be because some change in Pandas or SQLalchemy means Tapestry isn't handling these packages correctly.
3. If you could share your read FASTQ and assembly FASTA with me I could try it myself. You could post them here or please email them to me at johnomics at gmail.
